### ISSUE TITLE
Use 17 track

### ISSUE THREAD

**Issue by vicdilou** [fewieden/MMM-ShipmentTracking#5]
hi,
When I write 17track instead of DHL the mirror don't start.
How can I use 17 track ?

**Comment by fewieden** [comment]
Do you get any errors in the logs?

**Comment by vicdilou** [comment]
I don't know why but without changing anything it works.
Thank you

**Comment by D3rpi** [comment]
Hello, 
I am also having an issue with 17track.
My config looks like this: 
```
{
    module: 'MMM-ShipmentTracking',
    position: 'top_right',
    config: {
        tracking: {
            17track: ['0123456789123']
        },
``
When I use 17track, I get the config is broken error and the MM webpage does not load but if replace 17track with DHL all is well and the modules loads fine.

**Comment by fewieden** [comment]
you have to put quotes around 17track, because the string starts with a number

```
{
  module: 'MMM-ShipmentTracking',
  position: 'top_right',
  config: {
    tracking: {
      '17track': ['0123456789123']
    }
  }
}
```

**Comment by D3rpi** [comment]
Thanks. I now have a syntax error when I try to start the mirror. 

> Starting MagicMirror: v2.1.0
> Loading config ...
> Loading module helpers ...
> No helper found for module: alert.
> No helper found for module: clock.
> No helper found for module: calendar_monthly.
> Initializing new module helper ...
> Initializing new module helper ...
> Initializing new module helper ...
> No helper found for module: MMM-Globe.
> Initializing new module helper ...
> Initializing new module helper ...
> Initializing new module helper ...
> Initializing new module helper ...
> No helper found for module: helloworld.
> Initializing new module helper ...
> Initializing new module helper ...
> Initializing new module helper ...
**> WARNING! Could not validate config file. Please correct syntax errors. Starting with default configuration.**
> Loading module helpers ...
> No helper found for module: alert.
> No helper found for module: clock.
> No helper found for module: calendar_monthly.
> Initializing new module helper ...
> Initializing new module helper ...
> Initializing new module helper ...
> No helper found for module: MMM-Globe.
> Initializing new module helper ...
> Initializing new module helper ...
> Initializing new module helper ...
> Initializing new module helper ...
> No helper found for module: helloworld.
> Initializing new module helper ...
> Initializing new module helper ...
> Initializing new module helper ...
> **Whoops! There was an uncaught exception...
> [SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode]**
> MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
> If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
>
