### ISSUE TITLE
Integration of existing multi-tracking solution (deliveries.orrs.de)

### ISSUE THREAD

**Issue by 3DJupp** [fewieden/MMM-ShipmentTracking#7]
There is an existing solution, that supports a variety of tracking and shopping portals.
https://deliveries.orrs.de/sync/
You can use the mobile app for Android and Blackberry.

https://deliveries.orrs.de/sync/

What about implementing a solution like this?

I also asked the author about an remote access:
https://hilfe.orrs.de/1318/bietet-orrs-deliveries-eine-api

**Comment by fewieden** [comment]
As the author of the service said there will be no API available to integrate this service.
